// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type MoveParameterMove string

const (
	MoveParameterMoveHuman   MoveParameterMove = "human"
	MoveParameterMoveRandom  MoveParameterMove = "random"
	MoveParameterMoveMinimax MoveParameterMove = "minimax"
)

func (e MoveParameterMove) ToPointer() *MoveParameterMove {
	return &e
}

func (e *MoveParameterMove) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "human":
		fallthrough
	case "random":
		fallthrough
	case "minimax":
		*e = MoveParameterMove(v)
		return nil
	default:
		return fmt.Errorf("invalid value for MoveParameterMove: %v", v)
	}
}

type MoveParameter struct {
	CellIndex *int64
	Move      *MoveParameterMove
}
